// GENERATED by scripts/inject-css.mjs — do not edit; edit src/dsh/Files.css
// and re-run `npm run build`.
export const css = `/* changestab client styles. Not linked into any HTML: scripts/inject-css.mjs
   embeds this file as a string constant in the client bundle, because the
   dsh web shell's module loader has no asset pipeline. */
.dswFiles_root{position:relative;display:flex;flex-direction:column;height:100%;min-height:0}
/*The Changes tab's chip icon (the sidebar.right.pane.tab.title slot): the stock files chip icon's shape — flex:none, inheriting the chip's ink.*/
.dswFiles_tabTitleIcon{flex:none}
/*Nav column header: the root path row, reload, and the nav's own HIDE at the right end. Unmounts with the pane when the nav is collapsed.*/
.dswFiles_header{box-sizing:border-box;border-bottom:.5px solid var(--dsw-alias-border-l3);flex:none;align-items:center;gap:4px;height:38px;padding:0 0 0 8px;display:flex}
/*The nav column's toggle: a STATE PAIR, one control per state — HIDE (») in the nav's header, RESTORE («) in the view bar's right end while the nav is hidden. Both share this class so the pair reads as one control; each renders its own static double chevron, so no rotation. margin-left:auto pins the restore button to the view bar's right end and is a no-op in the nav header (the path row already takes the free space).*/
.dswFiles_navToggle{margin-left:auto;color:var(--dsw-alias-label-secondary);cursor:pointer;background:0 0;border:none;border-radius:6px;width:24px;height:24px;flex:none;display:inline-flex;align-items:center;justify-content:center}
.dswFiles_navToggle:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}
.dswFiles_navToggle:focus-visible{outline:1px solid var(--dsw-alias-state-focus-ring,currentColor);outline-offset:-1px}
/*Root path row, right-aligned: directories dimmed, the final segment full ink. The data-files-path-clipped attribute (written by an effect) fades the clipped start.*/
.dswFiles_path{white-space:nowrap;flex:auto;justify-content:flex-end;min-width:0;margin-right:12px;font-size:12px;display:flex;overflow:hidden}
.dswFiles_path[data-files-path-clipped]{mask-image:linear-gradient(90deg,#0000,#000 28px);-webkit-mask-image:linear-gradient(90deg,#0000,#000 28px)}
.dswFiles_pathText{flex:none;margin-right:auto}
.dswFiles_pathDirectory{color:var(--dsw-alias-label-tertiary)}
.dswFiles_pathName{color:var(--dsw-alias-label-primary)}
/*The header's 28px tool buttons (edit path, reload, show-hidden-files).*/
.dswFiles_tool{width:28px;height:28px;color:var(--dsw-alias-label-secondary);cursor:pointer;background:0 0;border:none;border-radius:6px;flex:none;justify-content:center;align-items:center;padding:6px;line-height:1;display:inline-flex}
.dswFiles_tool:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}
/*The divider is a draggable handle; FilesView writes --filez-nav on this element during the drag, with no re-render per pointermove.*/
.dswFiles_body{flex:1 1 0;align-items:stretch;min-height:0;padding:4px 16px 8px 16px;display:flex;--filez-nav:340px}
/*margin-right cancels the body's 16px right padding: the nav column's right edge IS the root's right edge. Keep in sync with .dswFiles_body's padding-right.*/
.dswFiles_browsePane{flex-direction:column;flex:0 1 var(--filez-nav);min-width:220px;min-height:0;margin-right:-16px;padding-left:8px;display:flex}
.dswFiles_divider{position:relative;flex:none;width:6px;cursor:col-resize;touch-action:none;user-select:none}
.dswFiles_divider::before{content:'';position:absolute;top:0;bottom:0;left:50%;width:1px;transform:translateX(-50%);background:var(--dsw-alias-border-l3)}
.dswFiles_divider:hover::before,.dswFiles_dividerActive::before{background:var(--dsw-alias-state-business-primary)}
.dswFiles_previewPane{flex-direction:column;flex:1 1 0;min-width:320px;padding-right:8px;display:flex;overflow:auto}
/*Collapsed: the view pane takes the nav column's place flush to the root's right edge — the -16px cancels the body's right padding, mirroring .dswFiles_browsePane.*/
.dswFiles_bodyNavHidden .dswFiles_previewPane{margin-right:-16px}
/*The file tree: directory levels indent 18px, rows are full-width 10px-radius*/
/*buttons, and a per-directory note row carries the level's*/
/*loading/empty/truncated/failed state. File rows pair a status letter with a*/
/*font cue on the name so the letter is never the only signal.*/
.dswFiles_tree{scrollbar-gutter:stable;flex:auto;min-height:0;margin-left:2px;padding:8px 8px 8px 0;overflow:auto}
.dswFiles_rowIcon{color:var(--dsw-alias-label-tertiary);flex:none}
/*A directory's level state that is not (yet) a listing.*/
.dswFiles_note{color:var(--dsw-alias-label-tertiary);margin:0;padding:3px 10px;font-size:12px;list-style:none}
.dswFiles_noteErr{color:var(--dsw-alias-state-error-primary)}
.dswFiles_previewEmpty{padding:20px;font-size:13px;line-height:18px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_previewImageWrap{flex:1 1 0;justify-content:center;align-items:center;min-height:0;display:flex;overflow:auto}
.dswFiles_previewImage{max-width:100%;max-height:100%;object-fit:contain;display:block}
.dswFiles_previewNote{position:sticky;left:0;padding:4px 8px;font-size:11px;line-height:16px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_previewCard{padding:16px;display:flex;flex-direction:column;gap:4px}
.dswFiles_previewCardName{color:var(--dsw-alias-label-primary);font-size:13px;font-weight:600;word-break:break-all}
.dswFiles_previewCardMeta{color:var(--dsw-alias-label-secondary);font-size:12.5px;line-height:18px}
.dswFiles_error{padding:4px 16px;font-size:12px;line-height:18px;color:var(--dsw-alias-state-error-primary)}
/*Right-edge fade: makes hidden horizontal overflow discoverable; shown only while more content lies to the right.*/
.dswFiles_diff{position:relative;flex:1 1 0;min-height:0;overflow:auto;display:flex;flex-direction:column;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12.5px;line-height:18px}
.dswFiles_diffCue{position:absolute;top:0;right:0;bottom:0;width:28px;pointer-events:none;background:linear-gradient(to left,rgba(0,0,0,.16),rgba(0,0,0,0));opacity:0;transition:opacity .15s ease;z-index:2}
.dswFiles_diffCueOn{opacity:1}
/*Sticky on both axes: the head stays put while the diff scrolls vertically and across the horizontal range.*/
.dswFiles_diffHead{position:sticky;top:0;left:0;z-index:1;background:var(--dsw-alias-bg-base);padding:8px 10px 6px;border-bottom:1px solid var(--dsw-alias-border-l3)}
/*The head row doubles as the ref surface: at rest it shows the file's path,
a click/selection on source text morphs it into the exact ref token. The
action cluster hugs the path/token (flex:0 1 auto — natural width, shrinking
with an ellipsis only when it runs out of room): buttons at the row's far
end would read as "acts on the file", not "acts on the ref". One line, fixed
height (never wraps); user-select off so a drag from the row into the file
text can't build a mixed-anchor selection the resolvers reject, and so
clicking the buttons never collapses the live selection.*/
.dswFiles_paneHead{display:flex;align-items:center;gap:6px;padding:6px 10px;border-bottom:1px solid var(--dsw-alias-border-l3);user-select:none;-webkit-user-select:none;min-height:30px}
.dswFiles_paneHeadPath{flex:0 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:600}
.dswFiles_paneHeadToken{flex:0 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:18px;color:var(--dsw-alias-label-primary)}
.dswFiles_paneHeadBtns{display:flex;gap:2px;align-items:center;flex:none}
.dswFiles_headBtn{cursor:pointer;background:0 0;border:none;border-radius:5px;padding:1px 5px;font-size:11px;line-height:18px;color:var(--dsw-alias-label-secondary);display:inline-flex;align-items:center;gap:3px;white-space:nowrap}
.dswFiles_headBtn:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}
.dswFiles_headBtnOn{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}
.dswFiles_diffMeta{padding-top:2px;font-size:11px;line-height:16px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_diffBinaryRow{display:flex;gap:8px;padding:8px;flex:1 1 0;min-height:0}
.dswFiles_diffBinaryPane{flex:1 1 0;min-width:0;min-height:0;display:flex;flex-direction:column;gap:4px}
.dswFiles_diffBinaryLabel{flex:none;font-size:11px;line-height:16px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_diffBinaryNone{flex:1 1 0;display:flex;align-items:center;justify-content:center;min-height:48px;font-size:12px;color:var(--dsw-alias-label-tertiary)}
/*One grid for the whole file (per-row grids would misalign the rows). The*/
/*text columns overflow their half and slide via the shared --diff-x, driven*/
/*by the container's horizontal scrollbar, so both halves scroll in sync with*/
/*the gutters pinned. The grid sits sticky-left over a zero-height spacer*/
/*(width = widest line, set by an effect) that provides the scroll range.*/
.dswFiles_diffGrid{display:grid;position:sticky;left:0;width:100%;grid-template-columns:44px minmax(0,1fr) 44px minmax(0,1fr);white-space:pre;align-content:start}
.dswFiles_diffGridU{grid-template-columns:44px minmax(0,1fr)}
.dswFiles_diffSpacer{flex:none;width:0;height:0}
.dswFiles_diffNo{text-align:right;padding:0 6px 0 2px;color:var(--dsw-alias-label-tertiary);user-select:none;font-variant-numeric:tabular-nums}
.dswFiles_diffNoDel{color:var(--dsw-alias-state-error-primary)}
.dswFiles_diffNoAdd{color:var(--dsw-alias-state-success-primary)}
/*Each cell is a clipping window at half the pane width; the inner span carries the line, translated by the shared --diff-x so both halves reveal overflow in lockstep.*/
.dswFiles_diffCell{padding:0 8px 0 0;overflow:hidden}
.dswFiles_diffCellIn{display:block;transform:translateX(var(--diff-x,0px))}
.dswFiles_cellDelO{background:rgba(229,83,75,.16)}
.dswFiles_cellDelN{background:rgba(229,83,75,.07)}
.dswFiles_cellAddO{background:rgba(46,160,67,.07)}
.dswFiles_cellAddN{background:rgba(46,160,67,.16)}
/*A mod row whose lines are identical (a move) or differ only in whitespace
(a re-alignment): a neutral tint that OVERRIDES the add/del color, so a
no-content-change reads as minor. After the cell colors so it wins the
cascade.*/
.dswFiles_cellModDim{background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.12))}
.dswFiles_noModDim{color:var(--dsw-alias-label-secondary)}
/*Intra-line change spans in a mod row: a stronger tint than the row-level cells so a few-character edit stands out.*/
.dswFiles_spanDel{background:rgba(229,83,75,.45)}
.dswFiles_spanAdd{background:rgba(46,160,67,.45)}
/*Theme-aware tints where color-mix exists (the fixed rgba values are the*/
/*fallback)*/
.dswFiles_diffGapCell{background:var(--dsw-alias-bg-layer-2,rgba(128,128,128,.10))}
.dswFiles_diffGapTxt{padding:2px 8px;font-size:11px;line-height:16px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_diffNN{color:var(--dsw-alias-label-tertiary)}
/*The nav column's split panes (VCS workspace only): the change log (its own
scroll region) on top, a movable horizontal divider, the changed-files list
filling the rest. Non-VCS / loading / error render a single pane (no split).*/
.dswFiles_panes{flex:1 1 0;min-height:0;display:flex;flex-direction:column}
/*flex:none + the inline height (treeH state, written directly during the
divider drag); 240px is the CSS default, 96px the drag's floor.*/
.dswFiles_logPane{flex:none;height:240px;min-height:96px;display:flex;flex-direction:column;min-width:0}
.dswFiles_logPane .dswFiles_tree{flex:1 1 0}
/*The horizontal divider: the vertical one's row-resize analog (same
pointer-capture pattern; the drag writes the log pane's height directly).*/
.dswFiles_hDivider{position:relative;flex:none;height:6px;cursor:row-resize;touch-action:none;user-select:none}
.dswFiles_hDivider::before{content:'';position:absolute;left:0;right:0;top:50%;height:1px;transform:translateY(-50%);background:var(--dsw-alias-border-l3)}
.dswFiles_hDivider:hover::before,.dswFiles_hDivider.dswFiles_dividerActive::before{background:var(--dsw-alias-state-business-primary)}
.dswFiles_filesPane{flex:1 1 0;min-height:96px;display:flex;flex-direction:column;min-width:0}
.dswFiles_filesPaneHead{flex:none;padding:4px 8px 2px 2px;font-size:10.5px;line-height:14px;color:var(--dsw-alias-label-tertiary)}
/*The selected change's full message (the tree's rows carry only the first
line): PLAIN text in the shell's proportional font — the message's own blank
lines are its paragraph structure, so pre-wrap keeps the author's layout
without interpreting markdown (commit text is untrusted input to this
read-only viewer; rendering it to HTML would need a sanitizer for nothing).
Self-scrolling, capped, so a long body never pushes the file list out of
view. Shown for any non-empty message, subject included.*/
.dswFiles_changeDescFull{flex:none;margin:0;padding:2px 8px 4px 2px;font-size:11.5px;line-height:15px;color:var(--dsw-alias-label-secondary);white-space:pre-wrap;word-break:break-word;max-height:120px;overflow-y:auto}
.dswFiles_filesScroll{flex:1 1 0;min-height:0;overflow:auto;scrollbar-gutter:stable;padding:0 8px 8px 0;margin-left:2px}
/*Change tree nav — the change log pane: the working-copy
row on top, a stack of commit rows below (newest first), each row drawing
its jj-log-style graph lanes to the left of its text. The lanes are
CSS-drawn (1px lines, not box-drawing glyphs — no font metrics to fight);
the row's height is 38px (3+16+1+15+3) so the node level sits 11px down,
where the first text line is centered. gap:0 keeps the vertical lines
continuous across rows. --filez-lanes (set inline) indents the rows'
content past the lane column.*/
.dswFiles_changeTree{flex:none;margin:2px 0 4px;padding:2px 8px 2px 0;display:flex;flex-direction:column;gap:0}
.dswFiles_changeRow{box-sizing:border-box;position:relative;flex:none;width:100%;cursor:pointer;background:0 0;border:none;border-radius:6px;padding:3px 8px 3px 0;text-align:left;display:flex}
.dswFiles_changeRow:hover{background:var(--dsw-alias-interactive-bg-hover)}
.dswFiles_changeRowSelected{background:var(--dsw-alias-interactive-bg-active,var(--dsw-alias-interactive-bg-hover))}
.dswFiles_changeRow:focus-visible{outline:1px solid var(--dsw-alias-state-focus-ring,currentColor);outline-offset:-1px}
/*The lane column: one 12px channel per lane, spanning the row's FULL height
(absolute, so the vertical lines cross the row paddings and stay continuous
across rows). The content column clears it.*/
.dswFiles_rowLanes{position:absolute;top:0;bottom:0;left:0;display:flex}
.dswFiles_rowContent{flex:1 1 0;min-width:0;display:flex;flex-direction:column;gap:1px;margin-left:calc(var(--filez-lanes,0) * 12px)}
.dswFiles_lane{position:relative;flex:none;width:12px}
.dswFiles_laneV{position:absolute;left:50%;width:1px;margin-left:-.5px;background:var(--dsw-alias-border-l2)}
.dswFiles_laneV.dswFiles_vT{top:0;height:11px}
.dswFiles_laneV.dswFiles_vB{top:11px;bottom:0}
.dswFiles_laneV.dswFiles_vT.dswFiles_vB{top:0;height:auto}
.dswFiles_laneH{position:absolute;top:11px;height:1px;margin-top:-.5px;background:var(--dsw-alias-border-l2)}
.dswFiles_laneH.dswFiles_hL{left:0;right:50%}
.dswFiles_laneH.dswFiles_hR{left:50%;right:0}
.dswFiles_laneH.dswFiles_hB{left:0;right:0}
.dswFiles_laneNode{position:absolute;top:3px;left:0;right:0;height:16px;display:flex;align-items:center;justify-content:center;z-index:1}
.dswFiles_changeLine{display:flex;align-items:center;gap:6px;min-width:0}
/*Node bullet: the diamond is the working copy, the circle a commit; hollow
= empty, the red slash an unresolved conflict (color carries health).*/
/*Node characters (jj's own log glyphs, text): @ working copy (accent, bold
— jj: green bold), ◆ immutable (bold — jj: bright cyan bold), × conflict
(red, bold — jj: red bold), ○ normal (dim, like the lane lines).*/
.dswFiles_changeGlyph{flex:none;font-size:12px;line-height:16px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_changeGlyph_wc{color:var(--dsw-alias-state-business-primary);font-weight:700}
.dswFiles_changeGlyph_immutable{color:var(--dsw-alias-label-secondary);font-weight:700}
.dswFiles_changeGlyph_conflict{color:var(--dsw-alias-state-error-primary);font-weight:700}
/*jj renders the id as its significant (unique) prefix, highlighted, + the
rest in grey — the host supplies the split (shortest(8)); git rows render
the plain short sha, unhighlighted.*/
.dswFiles_changeId{flex:none;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px;color:var(--dsw-alias-label-secondary)}
.dswFiles_changeIdSig{color:var(--dsw-alias-state-business-primary);font-weight:600}
.dswFiles_changeIdRest{color:var(--dsw-alias-label-tertiary)}
.dswFiles_changeWhen{flex:none;margin-left:auto;font-size:10.5px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_changeDesc{font-size:11.5px;line-height:15px;color:var(--dsw-alias-label-secondary);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
/*Scroll auto-load: the "loading older" note at the log's bottom edge while
the next page fetches. It clears the lane column like a row's content and
fades; it is a status, not a control — there is no "load less". It vanishes
when the page lands or the log is exhausted.*/
.dswFiles_logLoading{flex:none;margin-left:calc(var(--filez-lanes,0) * 12px);padding:4px 8px 6px;font-size:10.5px;line-height:14px;color:var(--dsw-alias-label-tertiary);animation:dswFiles_logLoadingPulse 1.2s ease-in-out infinite}
@keyframes dswFiles_logLoadingPulse{0%,100%{opacity:.45}50%{opacity:1}}

/*Bookmark (tinted fill) and tag (outlined) pills; at most 3 + a "+N" fold.*/
.dswFiles_changePill{flex:none;max-width:90px;overflow:hidden;text-overflow:ellipsis;font-size:10.5px;line-height:14px;padding:0 5px;border-radius:999px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);user-select:none;white-space:nowrap}
.dswFiles_changePillTag{background:0 0;border:1px solid var(--dsw-alias-border-l3);color:var(--dsw-alias-label-secondary)}
.dswFiles_changePillMore{color:var(--dsw-alias-label-tertiary)}
/*Pill variants: workspace names in the success tone (jj's working-copy
label), the @remote part dim, and the sync sigils — \`*\` an unsynced local
ref (warn), \`??\` a conflicted ref (error, bold).*/
.dswFiles_changePillWs{color:var(--dsw-alias-state-success-primary)}
.dswFiles_changePillRemote{color:var(--dsw-alias-label-tertiary)}
.dswFiles_changePillSigil{color:var(--dsw-alias-state-warn-primary);font-weight:700}
.dswFiles_changePillSigilConflict{color:var(--dsw-alias-state-error-primary)}
/*jj's change offset: a hidden/divergent change id renders as \`xyz/N\`
(N = position within the change, newest = 0) — bold, like the CLI's
change_offset label.*/
.dswFiles_changeIdOff{font-weight:700}
/*The CLI's commit labels, end of line: (hidden) dim, (divergent) and
(conflict) red (jj renders a mutable divergent commit in red).*/
.dswFiles_changeLabel{flex:none;font-size:10.5px;color:var(--dsw-alias-label-tertiary);white-space:nowrap}
.dswFiles_changeLabelDivergent{color:var(--dsw-alias-state-error-primary)}
.dswFiles_changeLabelConflict{color:var(--dsw-alias-state-error-primary)}
/*The selected change's file list: the files pane's content (the pane's
header names the selected change).*/
/*The changed-files list wears the stock file browser's row metrics (its
.root/.row/.name CSS): 13px/1.5 text, primary color, 5px 10px row padding,
6px gap, 18px per nesting level — the status badge takes the stock row's
16px icon slot, so names line up with a stock tree.*/
.dswFiles_changeFiles{margin:0 0 4px 0;padding:0;list-style:none;flex:none;font-size:var(--dsh-content-font-size-secondary,13px);line-height:1.5}
.dswFiles_changeFileRow{box-sizing:border-box;display:flex;align-items:center;gap:6px;min-width:0;width:100%;color:inherit;font:inherit;cursor:pointer;background:0 0;border:none;border-radius:var(--dsw-radius-md,5px);padding:5px 10px;text-align:left}
.dswFiles_changeFileRow:hover{background:var(--dsw-alias-interactive-bg-hover)}
.dswFiles_changeFileName{min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dswFiles_changeFilesLoading{padding:3px 10px;font-size:12px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_changeFilesEmpty{padding:3px 10px;font-size:12px;color:var(--dsw-alias-label-tertiary)}
/*The selected change's changed files, directory-grouped: a directory is a
row of its own (folder icon + name, the stock file browser's row pattern —
no disclosure chevron) that toggles its nested level; files sit at their
exact depth. Directories are expanded by default.*/
.dswFiles_fileItem{margin:0;padding:0}
.dswFiles_changeDirRow{box-sizing:border-box;display:flex;align-items:center;gap:6px;min-width:0;width:100%;color:inherit;font:inherit;cursor:pointer;background:0 0;border:none;border-radius:var(--dsw-radius-md,5px);padding:5px 10px;text-align:left}
.dswFiles_changeDirRow:hover{background:var(--dsw-alias-interactive-bg-hover)}
.dswFiles_changeDirRow:focus-visible{outline:1px solid var(--dsw-alias-state-focus-ring,currentColor);outline-offset:-1px}
.dswFiles_changeDirName{min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dswFiles_changeFilesLevel{margin:0;padding:0 0 0 18px;list-style:none}
.dswFiles_changeFileRow:focus-visible{outline:1px solid var(--dsw-alias-state-focus-ring,currentColor);outline-offset:-1px}
.dswFiles_changeFileRowSelected,.dswFiles_changeFileRowSelected:hover{background:var(--dsw-alias-interactive-bg-active,var(--dsw-alias-interactive-bg-hover))}
/*Non-VCS workspace: the change tree has nothing to show; the note hands the
  user to the official file viewer.*/
.dswFiles_noVcs{flex:none;padding:6px 8px;border:1px dashed var(--dsw-alias-border-l3);border-radius:8px;margin:6px 8px 2px;display:flex;flex-direction:column;gap:6px}
.dswFiles_noVcsText{font-size:11.5px;line-height:15px;color:var(--dsw-alias-label-secondary)}
.dswFiles_noVcsHint{font-size:11px;line-height:15px;color:var(--dsw-alias-label-tertiary)}
.dswFiles_noVcsBtn{cursor:pointer;align-self:flex-start;border:none;border-radius:6px;background:var(--dsw-alias-bg-layer-2);padding:3px 10px;font-size:11px;line-height:16px;color:var(--dsw-alias-label-primary)}
.dswFiles_noVcsBtn:hover{background:var(--dsw-alias-interactive-bg-hover)}
/*The status badge occupies the stock row's 16px icon slot, so the name
column lines up with a stock file tree.*/
.dswFiles_badge{flex:none;width:16px;text-align:center;font-size:10.5px;font-weight:700;line-height:14px}
.dswFiles_badgeA{color:var(--dsw-alias-state-success-primary)}
.dswFiles_badgeM{color:var(--dsw-alias-state-warn-primary)}
.dswFiles_badgeD{color:var(--dsw-alias-state-error-primary)}
.dswFiles_badgeR{color:var(--dsw-alias-state-business-primary)}
.dswFiles_badgeC{color:var(--dsw-alias-state-error-primary)}
.dswFiles_badgeU{color:var(--dsw-alias-state-success-primary)}
/*padding-right 0: the chevron's right edge aligns with the scroll content's right edge — it sits above the top of the scrollbar.*/
.dswFiles_paneToggle{display:flex;gap:2px;flex:none;padding:6px 0 0 8px}`;
