// GENERATED by scripts/inject-icon.mjs — do not edit; edit
// assets/icons/changestab-icon.svg and re-run `npm run build`.
export const iconSvg = `<defs>
    <g id="changestab-kn">
      <circle cx="0" cy="-47.6" r="2.7"/>
      <rect x="-3.2" y="-46" width="6.4" height="11" rx="2.8"/>
      <rect x="-8" y="-35" width="16" height="4.5" rx="2.25"/>
      <path d="M0 0 C2.2 -4.5 3.4 -9 3.4 -14 V-30 H-3.4 V-14 C-3.4 -9 -2.2 -4.5 0 0 Z"/>
    </g>
    <mask id="changestab-cut" maskUnits="userSpaceOnUse" x="0" y="0" width="64" height="64">
      <rect width="64" height="64" fill="#fff"/>
      <g transform="translate(25 40) rotate(45)"><use href="#changestab-kn" fill="#000" stroke="#000" stroke-width="5"/></g>
    </mask>
  </defs>
  <g id="changestab-branches" mask="url(#changestab-cut)">
    <g fill="none" stroke="currentColor" stroke-width="5" stroke-linecap="round" stroke-linejoin="round">
      <line x1="25" y1="15" x2="25" y2="54"/>
      <path d="M25 40 C35 40 41 42 46 47"/>
    </g>
    <g fill="currentColor">
      <path d="M25 8 L32 15 L25 22 L18 15 Z"/>
      <path d="M25 33 L32 40 L25 47 L18 40 Z"/>
      <path d="M25 47 L32 54 L25 61 L18 54 Z"/>
      <path d="M46 40 L53 47 L46 54 L39 47 Z"/>
    </g>
  </g>
  <g id="changestab-knife" transform="translate(25 40) rotate(45)" fill="currentColor"><use href="#changestab-kn"/></g>`;
