// Build step: assets/icons/changestab-icon.svg is the single source of
// truth for the brand glyph (the plugin-manager icon and the in-app
// chip/capsule glyph both derive from it). The dsh web shell's module
// loader has no asset pipeline, so the glyph must ship inside the client
// bundle: this script embeds the SVG into src/dsh/icon-svg.generated.ts (a
// committed, deterministic module) that client.tsx mounts once per document
// as a hidden sprite; every visible glyph is a plain <use> of the sprite.
// Runs in `npm run build` after inject-css.mjs; the output is only
// rewritten when the SVG changed.
//
// The markup is rewritten as it is embedded: the ids are namespaced (so the
// sprite can never collide with other ids on the page), and the two
// top-level drawing groups get ids (so the <use> instances need no
// per-instance id handling at render time). A rewrite that no longer matches
// fails the build — the icon changed, and this table must follow it.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const svgPath = join(root, "assets", "icons", "changestab-icon.svg");
const outPath = join(root, "src", "dsh", "icon-svg.generated.ts");
const NS = "changestab";

const svg0 = readFileSync(svgPath, "utf8").replace(/\r\n/g, "\n").replace(/\s+$/, "");

function rewrite(svg, from, to, expected, label) {
  const n = svg.split(from).length - 1;
  if (n !== expected) {
    console.error(`inject-icon: expected ${expected} of ${label} in ${svgPath}, found ${n} — the icon changed; update this script's rewrite table.`);
    process.exit(1);
  }
  return svg.split(from).join(to);
}

let svg = svg0;
svg = rewrite(svg, 'id="kn"', `id="${NS}-kn"`, 1, 'id="kn"');
svg = rewrite(svg, 'id="cut"', `id="${NS}-cut"`, 1, 'id="cut"');
svg = rewrite(svg, 'href="#kn"', `href="#${NS}-kn"`, 2, 'href="#kn"');
svg = rewrite(svg, "url(#cut)", `url(#${NS}-cut)`, 1, "url(#cut)");
svg = rewrite(svg, `<g mask="url(#${NS}-cut)">`, `<g id="${NS}-branches" mask="url(#${NS}-cut)">`, 1, "the branches group");
svg = rewrite(svg, `<g transform="translate(25 40) rotate(45)" fill="currentColor">`, `<g id="${NS}-knife" transform="translate(25 40) rotate(45)" fill="currentColor">`, 1, "the knife group");
const titleRe = /<title>[\s\S]*?<\/title>/;
if (!titleRe.test(svg)) {
  console.error(`inject-icon: expected a <title> in ${svgPath} — the icon changed; update this script.`);
  process.exit(1);
}
svg = svg.replace(titleRe, "");
// The root color is for standalone display only; instances get their ink
// from the <use> site, so it must not ride along.
svg = rewrite(svg, ' color="#836042"', "", 1, "the root color attribute");

// Embed the INNER content (the client sets it as the hidden sprite's
// innerHTML, which would double-nest an <svg> root).
const openEnd = svg.indexOf(">") + 1;
if (openEnd === 0 || !svg.endsWith("</svg>")) {
  console.error(`inject-icon: unexpected <svg> shape in ${svgPath} — the icon changed; update this script.`);
  process.exit(1);
}
const inner = svg.slice(openEnd, svg.length - "</svg>".length).trim();
for (const tag of ["defs", "g", "mask"]) {
  const openN = (inner.match(new RegExp(`<${tag}[ >]`, "g")) || []).length;
  const closeN = (inner.match(new RegExp(`</${tag}>`, "g")) || []).length;
  if (openN !== closeN) {
    console.error(`inject-icon: unbalanced <${tag}> in the embedded glyph (${openN} vs ${closeN})`);
    process.exit(1);
  }
}
for (const id of [`${NS}-kn`, `${NS}-cut`, `${NS}-branches`, `${NS}-knife`]) {
  if (!inner.includes(`id="${id}"`)) {
    console.error(`inject-icon: expected id "${id}" in the embedded glyph`);
    process.exit(1);
  }
}

const escaped = inner.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
const out =
  "// GENERATED by scripts/inject-icon.mjs — do not edit; edit\n" +
  "// assets/icons/changestab-icon.svg and re-run `npm run build`.\n" +
  "export const iconSvg = `" + escaped + "`;\n";
const prev = existsSync(outPath) ? readFileSync(outPath, "utf8") : null;
if (prev !== out) {
  writeFileSync(outPath, out);
  console.log(`inject-icon: wrote ${outPath} (${Buffer.byteLength(out)} bytes)`);
} else {
  console.log("inject-icon: up to date");
}
